### ISSUE TITLE
useStrapiUrl is not defined

### ISSUE THREAD

**Issue by nikosdrog** [kuizuo/vitesse-nuxt-strapi#3]
Hello there. 
I run npm run dev after the installations and i m getting th useStrapiUrl is not defined on the front end.

**Comment by kuizuo** [comment]
Make sure the `@nuxtjs/strapi` module is installed. In my tests, there was no case where `useStrapiUrl is not defined`

**Comment by nikosdrog** [comment]
Yes the `@nuxtjs/strapi` is installed. I use node v18.12.1 on Ubuntu OS
